# Generated by Django 2.0.9 on 2019-06-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0005_auto_20190603_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='faculty_email_address',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='school',
        ),
    ]
