# Generated by Django 2.0.9 on 2019-05-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_auto_20190520_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='school',
            field=models.CharField(default='Rice University', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('no_faculty_info', 'No Faculty Info'), ('pending_faculty', 'Pending Faculty'), ('confirmed_faculty', 'Confirmed Faculty'), ('rejected_faculty', 'Rejected Faculty')], default='no_faculty_info', max_length=255),
        ),
    ]
