# Generated by Django 2.0.9 on 2019-06-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0004_auto_20190603_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='ox_accounts_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
