# Generated by Django 2.0.9 on 2019-10-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0006_auto_20190603_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
