# Generated by Django 2.0.9 on 2019-10-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0007_verification_celery_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='celery_task_id',
            new_name='task_id',
        ),
    ]
