# Generated by Django 2.0.9 on 2019-05-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('security_token', models.CharField(max_length=255)),
                ('sandbox', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Salesforce Settings',
            },
        ),
    ]
